apiVersion: apps/v1
kind: Deployment
metadata:
    name: bl-scale
    labels:
        app: bl-scale
spec:
    selector:
        matchLabels:
            app: bl-scale
    strategy:
        rollingUpdate:
          maxSurge: 25%
          maxUnavailable: 25%
        type: RollingUpdate
    template:
        metadata:
            labels:
                app: bl-scale
        spec:
            containers:
                - env:
                    - name: ALG_SUB_PACKAGE
                      valueFrom:
                        configMapKeyRef:
                          key: ALG_SUB_PACKAGE
                          name: bl-scale-config-38mx
                    - name: ALG_NAME
                      valueFrom:
                        configMapKeyRef:
                          key: ALG_NAME
                          name: bl-scale-config-38mx
                    - name: GOOGLE_APPLICATION_CREDENTIALS
                      value: "/var/run/secret/cloud.google.com/bl-scale_key.json"
                  volumeMounts:
                  - name: "cred-key"
                    mountPath: "/var/run/secret/cloud.google.com"
                  image: gcr.io/breakthrough-listen-sandbox/bl-scale:energy-detection-latest
                  imagePullPolicy: Always
                  name: bl-scale-energy-detection
                  terminationMessagePath: /dev/termination-log
                  terminationMessagePolicy: File
                  resources:
                      # limits:
                      #     cpu: "15000m"
                      #     memory: "30G"
                      requests:
                          cpu: "7000m"
                          memory: "12G"
            volumes:
              - name: "cred-key"
                secret:
                  secretName: "bl-scale-cred-key"
            nodeSelector:
                cloud.google.com/gke-nodepool: algo-compute-pool
            dnsPolicy: ClusterFirst
            restartPolicy: Always
            schedulerName: default-scheduler
            securityContext: {}
            terminationGracePeriodSeconds: 300
