apiVersion: apps/v1
kind: DaemonSet
metadata:
    name: bl-scale
    labels:
        app: bl-scale
    namespace: default
spec:
    selector:
        matchLabels:
            app: bl-scale
    updateStrategy:
        rollingUpdate:
            maxUnavailable: 25%
        type: RollingUpdate
    template:
        metadata:
            labels:
                app: bl-scale
        spec:
            containers:
                - env:
                    - name: ALG_SUB_PACKAGE
                      value: energy_detection
                    - name: ALG_NAME
                      value: energy_detection
                    - name: GOOGLE_APPLICATION_CREDENTIALS
                      value: "/var/run/secret/cloud.google.com/bl-scale_key.json"
                  volumeMounts:
                  - name: "cred-key"
                    mountPath: "/var/run/secret/cloud.google.com"
                  image: gcr.io/breakthrough-listen-sandbox/bl-scale:energy-detection-latest
                  imagePullPolicy: Always
                  name: bl-scale-energy-detection
                  terminationMessagePath: /dev/termination-log
                  terminationMessagePolicy: File
            volumes:
              - name: "cred-key"
                secret:
                  secretName: "bl-scale-cred-key"
            dnsPolicy: ClusterFirst
            restartPolicy: Always
            schedulerName: default-scheduler
            securityContext: {}
            terminationGracePeriodSeconds: 30
