apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: bl-scale-flask
    name: bl-scale-flask
spec:
    replicas: 1
    selector:
        matchLabels:
            app: bl-scale-flask
    strategy:
        rollingUpdate:
            maxSurge: 25%
            maxUnavailable: 25%
        type: RollingUpdate
    template:
        metadata:
            labels:
                app: bl-scale-flask
        spec:
            containers:
            - env:
                - name: GOOGLE_APPLICATION_CREDENTIALS
                  value: "/var/run/secret/cloud.google.com/bl-scale_key.json"
              volumeMounts:
              - name: "cred-key"
                mountPath: "/var/run/secret/cloud.google.com"
              image: gcr.io/breakthrough-listen-sandbox/bl-scale:webapp-latest
              imagePullPolicy: Always
              name: bl-scale-flask
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
            volumes:
              - name: "cred-key"
                secret:
                  secretName: "bl-scale-cred-key"
            dnsPolicy: ClusterFirst
            restartPolicy: Always
            schedulerName: default-scheduler
            securityContext: {}
            terminationGracePeriodSeconds: 30
